node {
    def built_img = ''
    stage('Checkout git repo') {
      git branch: 'master', url: params.git_repo
    }
    stage('Build and push Docker image') {
      sh(script: "WEB_IMAGE_NAME=${acr_username}.azurecr.io/azure-vote-front:kube${BUILD_NUMBER}", returnStdout: true)
      sh(script: "docker build -t $WEB_IMAGE_NAME ./azure-vote", returnStdout: true)
      sh(script: "docker login ${acr_username}.azurecr.io -u ${acr_username} -p ${acr_password}", returnStdout: true)
      sh(script: "docker push $WEB_IMAGE_NAME", returnStdout: true)
    }
    stage('Unit Tests') {
      sh 'echo test'
    }
    stage('Browser Tests'){
        parallel(
            "Edge":{sh 'echo test'},
            "Firefox":{sh 'echo test'},
            "Chrome":{sh 'echo test'}
            )
    }
    stage('Deploy into k8s') {
      sh(script: "cat cicd/k8s.yaml | sed -e 's/build_number/${BUILD_NUMBER}/g' -e 's/YourACRName/${acr_username}/g' | kubectl apply -f - --kubeconfig /var/lib/jenkins/.kube/config", returnStdout: true)
    }
}
